---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
    # there are 4, which one do we access?
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
