---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deploy
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
      name: codeserver-po
  template:
    metadata:
      name: codeserver-po
      labels:
        app: codeserver
        name: codeserver-po
    spec:
      volumes:
        - name: codeserver-vol
          persistentVolumeClaim:
            claimName: codeserver-pvc
      containers:
        - name: codeserver-container
          image: lscr.io/linuxserver/code-server:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: codeserver-cm
            - secretRef:
                name: codeserver-secret
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: codeserver-vol
              mountPath: /config/workspace

---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-svc
spec:
  type: ClusterIP
  selector:
    app: codeserver
    name: codeserver-po
  ports:
    - port: 8080
      targetPort: 8443

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-cm
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-cm
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: 127.0.0.1.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-secret
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeserver-ing
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-ing
spec:
  ingressClassName: nginx
  rules:
    - host: codeserver.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeserver-svc
                port:
                  number: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage-retain
    resources:
      requests:
        storage: 1Gi
