apiVersion: v1
items:
- apiVersion: v1
  data:
    BGG_DB_HOST: dev-bggdb-svc.dev-ns.svc.cluster.local
    BGG_DB_USER: root
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"BGG_DB_HOST":"dev-bggdb-svc.dev-ns.svc.cluster.local","BGG_DB_USER":"root"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"env":"dev"},"name":"dev-bgg-cm-82tgk68kb6","namespace":"dev-ns"}}
    labels:
      env: dev
    name: dev-bgg-cm-82tgk68kb6
    namespace: dev-ns
- apiVersion: v1
  data:
    BGG_DB_PASSWORD: Y2hhbmdlaXQ=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"BGG_DB_PASSWORD":"Y2hhbmdlaXQ="},"kind":"Secret","metadata":{"annotations":{},"labels":{"env":"dev"},"name":"dev-bgg-secret-k8tc9ctc69","namespace":"dev-ns"},"type":"Opaque"}
    labels:
      env: dev
    name: dev-bgg-secret-k8tc9ctc69
    namespace: dev-ns
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"bgg","env":"dev","name":"bggapp-svc"},"name":"dev-bggapp-svc","namespace":"dev-ns"},"spec":{"ports":[{"port":80,"targetPort":3000}],"selector":{"app":"bgg","env":"dev","name":"bggapp-po"},"type":"LoadBalancer"}}
    labels:
      app: bgg
      env: dev
      name: bggapp-svc
    name: dev-bggapp-svc
    namespace: dev-ns
  spec:
    ports:
    - port: 80
      targetPort: 3000
    selector:
      app: bgg
      env: dev
      name: bggapp-po
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"bgg","env":"dev","name":"bggdb-svc"},"name":"dev-bggdb-svc","namespace":"dev-ns"},"spec":{"ports":[{"port":3306,"targetPort":3306}],"selector":{"app":"bgg","env":"dev","name":"bggdb-po"},"type":"ClusterIP"}}
    labels:
      app: bgg
      env: dev
      name: bggdb-svc
    name: dev-bggdb-svc
    namespace: dev-ns
  spec:
    ports:
    - port: 3306
      targetPort: 3306
    selector:
      app: bgg
      env: dev
      name: bggdb-po
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"bgg","env":"dev","name":"bggapp-deploy"},"name":"dev-bggapp-deploy","namespace":"dev-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"bgg","env":"dev","name":"bggapp-po"}},"strategy":{"rollingUpdate":{"maxSurge":0,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"bgg","env":"dev","name":"bggapp-po"},"name":"bggapp-po"},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"dev-bgg-cm-82tgk68kb6"}},{"secretRef":{"name":"dev-bgg-secret-k8tc9ctc69"}}],"image":"stackupiss/bgg-backend:v2","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/healthz","port":3000}},"name":"bggapp-container","ports":[{"containerPort":3000}],"readinessProbe":{"httpGet":{"path":"/healthz","port":3000}}}]}}}}
    labels:
      app: bgg
      env: dev
      name: bggapp-deploy
    name: dev-bggapp-deploy
    namespace: dev-ns
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: bgg
        env: dev
        name: bggapp-po
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: bgg
          env: dev
          name: bggapp-po
        name: bggapp-po
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: dev-bgg-cm-82tgk68kb6
          - secretRef:
              name: dev-bgg-secret-k8tc9ctc69
          image: stackupiss/bgg-backend:v2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          name: bggapp-container
          ports:
          - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"bgg","env":"dev","name":"bggdb-deploy"},"name":"dev-bggdb-deploy","namespace":"dev-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"bgg","env":"dev","name":"bggdb-po"}},"template":{"metadata":{"labels":{"app":"bgg","env":"dev","name":"bggdb-po"},"name":"bggdb-po"},"spec":{"containers":[{"image":"stackupiss/bgg-database:v1","imagePullPolicy":"IfNotPresent","name":"bggdb-container","ports":[{"containerPort":3306}]}]}}}}
    labels:
      app: bgg
      env: dev
      name: bggdb-deploy
    name: dev-bggdb-deploy
    namespace: dev-ns
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: bgg
        env: dev
        name: bggdb-po
    template:
      metadata:
        labels:
          app: bgg
          env: dev
          name: bggdb-po
        name: bggdb-po
      spec:
        containers:
        - image: stackupiss/bgg-database:v1
          imagePullPolicy: IfNotPresent
          name: bggdb-container
          ports:
          - containerPort: 3306
kind: List
metadata: {}
