apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: dev-ns

namePrefix: dev-

commonLabels:
  env: dev

replicas:
  # name of resource
  - name: bggapp-deploy
    count: 1

images:
  - name: stackupiss/bgg-backend
    newTag: v2

configMapGenerator:
  - name: bgg-cm
    behavior: create
    literals:
      - BGG_DB_USER=root
      - BGG_DB_HOST=dev-bggdb-svc.dev-ns.svc.cluster.local
      # need to put in ourself the changes

secretGenerator:
  - name: bgg-secret
    behavior: create
    literals:
      - BGG_DB_PASSWORD=changeit
      # no need to be base64
