---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy
spec:
  # if replicas 2 will have a problem because only got 1 pvc, cannot share, must use stateful sets where kubernetes will create 1 disk for each pod according to the template
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bgg
        name: bggdb-po
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: bggdb-pvc
      containers:
        - name: bggdb-container
          image: stackupiss/bgg-database:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data-vol
              mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-po
  ports:
    - port: 3306
      targetPort: 3306
