---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mynginx-cm
  namespace: dev
  labels:
    name: mynginx-cm
data:
  index.html: | 
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Document</title>
    </head>
    <body>
      <h1>Hello world</h1>
    </body>
  </html>


about.html: |
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Document</title>
    </head>
    <body>
      <h1>Hi my name is fred</h1>
    </body>
    </html>



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deploy
  namespace: dev
  labels:
    name: mynginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mynginx-deploy
  template:
  # this is the pod
    metadata:
      name: mynginx-deploy
      labels:
        name: mynginx-deploy
    spec:
      volumes:
      - name: tmp-vol
        emptyDir: {} 
      - name: html-files
        configMap:
          name: mynginx-cm
      containers:
        - name: mynginx-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tmp-vol
            mountPath: /opt/tmp
            - name: html-files
            mountPath: /usr/share/nginx/html
            readOnly: true



